# Cloudflare Workers configuration for Auth API
name = "tunel-auth-api"
main = "workers/auth-api.ts"
compatibility_date = "2024-01-01"

# Environment variables
[vars]
JWT_SECRET = "tunel-jwt-secret-key-2024-production"

# D1 Database binding (will be configured after database creation)
# [[d1_databases]]
# binding = "DB"
# database_name = "tunel-db" 
# database_id = "placeholder-will-be-updated"